version: '3.8'
services:
  psql:
    container_name: psql
    image: postgres:14.1-alpine

    restart: always
    environment:
      - POSTGRES_DB=${PSQL_DATABASE}
      - POSTGRES_USER=${PSQL_USERNAME}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
    ports:
      - '5435:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
volumes:
  psql:
    driver: local
